# creates service account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sample
--- 

# Create a role in default namespace

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: ns-read-only
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "list"]

--- 

# Role Bidning: Associating a role to either a user or service Account
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ns-read-only
  namespace: default
subjects:
- kind: ServiceAccount
  name: sample
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role 
  name: ns-read-only
  apiGroup: rbac.authorization.k8s.io