# frontend deployment, lb service 
# backend deployment, clusterip service 
# mysql deployment, clusterip service 
# job to inject the schema 

apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:                      
    tier: frontend
spec:
  containers:
  - name: frontend
    image: docker.io/sanraman/expense-frontend
    ports:
    - containerPort: 80

--- 
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
spec:
  type: LoadBalancer
  selector:
    tier: frontend
  ports:
    - name: http
      protocol: TCP
      port: 80                 # service listens on 80 
      targetPort: 80           # requests received by this service will be forwareded to pods port 
  